[tool.pytest.ini_options]
addopts = "--headed --html=report.html --self-contained-html"
html = true
html_title = "Test Report"
html_logo = "logo.png"
html_static_dir = "static"
html_css_files = ["static/style.css"]
html_js_files = ["static/script.js"]
html_favicon = "static/favicon.ico"
html_additional_html = "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>"

[tool.playwright]
chromium = true
firefox = true
webkit = true
